INSERT INTO users (user_name, city_name, city_id, first_name, last_name, pic, skill)
VALUES
    ('Silvershadow','New York City',1,'Elizabeth', 'Stanley', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasdictablanditiis.jpg','crotchet'),
    ('StarGazer23','Buffalo',2,'Rosy', 'Hernandez', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasautreprehenderit.jpg', 'cooking'),
    ('ElectricP','Rochester',3, 'Avery', 'P', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/aspernaturnonsapiente.jpg', 'art/crafts'),
    ('MoonlightW','Yonkers',4,'Ashley','H', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/autautdeserunt.jpg', 'music'),
    ('NeonSW','Syracuse',5,'Neo', 'Hannes', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/consequaturdelectusquis.jpg', 'photography'),
    ('MysticScribe','Albany',6,'Janet', 'Lowes', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/autautdeserunt.jpg', 'reading'),
    ('FireflyDream','New Rochelle',7, 'Raven', 'Escober', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/utquamut.jpg', 'music'),
    ('QuantumJester','Long Beach',8,'Ricardo', 'Tu', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/nesciuntrerumlibero.jpg', 'planting'),
    ('CosmicExplorer','Long Beach',8,'Arthor', 'Winofred', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/autemporroplaceat.jpg', 'photography'),
    ('VelvetVoy', 'Long Beach',8, 'Benny', 'Bragg', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/doloribusquitempora.jpg', 'cooking'),
    ('Serene12','Albany',6,'Francine', 'Lopez', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/utquamut.jpg', 'crotchet'),
    ('Solar','New York City',1,'Celina', 'Cruz', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/enimpariaturoptio.jpg', 'arts/crafts'),
    ('Midnight90','Buffalo',2,'David', 'Frater', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/aspernaturnonsapiente.jpg', 'reading'),
    ('EnigmaEagle','Syracuse',5,'Joan', 'Lorenzo', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/nonipsaet.jpg', 'music'),
    ('AuroraSK','Rochester',3,'Velma', 'Brown', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasdictablanditiis.jpg', 'planting'),
    ('SolarFlare','New York City',1,'Carol', 'Jack', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/utquamut.jpg', 'photography'),
    ('EchoSport','Yonkers',4,'Jeniffer', 'Rodriguez', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/enimpariaturoptio.jpg', 'sports'),
    ('NebulaNomad','New Rochelle',7,'Xavier', 'Montanna', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/velitnonquibusdam.jpg','arts/crafts'),
    ('Radiant78','Buffalo',2,'Luis', 'Smith', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/remtemporavelit.jpg', 'sports'),
    ('Ember53','Syracuse',5,'Bryana', 'Miller', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/etporroalias.jpg', 'cooking'),
    ('Pheonix','Yonkers',4,'Kai', 'Jones', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/velitnonquibusdam.jpg', 'crotchet'),
    ('ShadowFrost','Buffalo',2,'Adam','Williams', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/delenitiestdolorum.jpg', 'fitness'),
    ('KristalCraft','Rochester',3,'Krysta', 'Johnson', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/sitlaborecorrupti.jpg', 'fitness'),
    ('DreamBiker','New York City',1,'Olivia', 'White', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/dolordoloremassumenda.jpg', 'biking'),
    ('OceanicOracle','Albany',6,'Kevin', 'Anderson', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/sitlaborecorrupti.jpg', 'swimming');