INSERT INTO users (user_name, city, first_name, last_name, pic, skill)
VALUES
    ('silvershadow','newyorkcity','elizabeth', 'stanley', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasdictablanditiis.jpg','crotchet'),
    ('StarGazer23','Buffalo','Rosy', 'Hernandez', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasautreprehenderit.jpg', 'cooking'),
    ('ElectricP','Rochester', 'Avery', 'P', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/aspernaturnonsapiente.jpg', 'art/crafts'),
    ('MoonlightW','Yonkers','Ashley','H', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/autautdeserunt.jpg', 'music'),
    ('NeonSW','Syracuse','Neo', 'Hannes', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/consequaturdelectusquis.jpg', 'photography'),
    ('MysticScribe','Albany','Janet', 'Lowes', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/autautdeserunt.jpg', 'reading'),
    ('FireflyDream','New Rochelle', 'Raven', 'Escober', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/utquamut.jpg', 'music'),
    ('QuantumJester','Long Beach', 'Ricardo', 'Tu', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/nesciuntrerumlibero.jpg', 'planting'),
    ('CosmicExplorer','Long Beach', 'Arthor', 'Winofred', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/autemporroplaceat.jpg', 'photography'),
    ('VelvetVoy', 'Long Beach', 'Benny', 'Bragg', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/doloribusquitempora.jpg', 'cooking'),
    ('Serene12','Albany','Francine', 'Lopez', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/utquamut.jpg', 'crotchet'),
    ('Solar','New York City', 'Celina', 'Cruz', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/enimpariaturoptio.jpg', 'arts/crafts'),
    ('Midnight90','Buffalo', 'David', 'Frater', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/aspernaturnonsapiente.jpg', 'reading'),
    ('EnigmaEagle','Syracuse','Joan', 'Lorenzo', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/nonipsaet.jpg', 'music'),
    ('AuroraSK','Rochester','Velma', 'Brown', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasdictablanditiis.jpg', 'planting'),
    ('SolarFlare','New York City','Carol', 'Jack', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/utquamut.jpg', 'photography'),
    ('EchoSport','Yonkers','Jeniffer', 'Rodriguez', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/enimpariaturoptio.jpg', 'sports'),
    ('NebulaNomad','New Rochelle','Xavier', 'Montanna', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/velitnonquibusdam.jpg','arts/crafts'),
    ('Radiant78','Buffalo','Luis', 'Smith', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/remtemporavelit.jpg', 'sports'),
    ('Ember53','Syracuse','Bryana', 'Miller', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/etporroalias.jpg', 'cooking'),
    ('Pheonix','Yonkers','Kai', 'Jones', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/velitnonquibusdam.jpg', 'crotchet'),
    ('ShadowFrost','Poughkeepsie','Adam','Williams', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/delenitiestdolorum.jpg', 'fitness'),
    ('KristalCraft','Rochester','Krysta', 'Johnson', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/sitlaborecorrupti.jpg', 'fitness'),
    ('DreamBiker','New York City','Olivia', 'White', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/dolordoloremassumenda.jpg', 'biking'),
    ('OceanicOracle','Albany','Kevin', 'Anderson', 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/sitlaborecorrupti.jpg', 'swimming');